name = "BlossomMatching"
uuid = "664ebbd3-01ea-5ff0-9621-55aaaf3546e3"
authors = ["Mathieu Besançon <mathieu.besancon@gmail.com>"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
